### PR TITLE
Updated mousetrap reference

### PR DESCRIPTION
**Pull request by kloudi-tech**
Updated mousetrap reference with a publically hosted folk of mousetrap by kloudi-tech where useCapture has been exposed with a default value of true.

This should close Issue #455

### CODE REVIEW

**Comment by asabaylus** [comment]
Thanks!

**Comment by nitishMehrotra** [comment]
@asabaylus There has been PR in mousetrap that is open since 2017 for this change. 

https://github.com/ccampbell/mousetrap/pull/400

It doesn't seem like it will get merge. Hence I started maintaining a separate folk.

**Comment by asabaylus** [comment]
@kloudi-tech thanks I’ll give him a few days to reply to my comment on the PR https://github.com/ccampbell/mousetrap/pull/400#issuecomment-688419909

If no response are you planning to maintain mousetrap? Possibly Craig would like someone to maintain

**Comment by nitishMehrotra** [comment]
I'll be maintaining the folk that we have at @kloudi-tech (https://github.com/kloudi-tech/mousetrap)

Majorly making sure that the upstreams doesn't have any conflict with the changes that we have made around useCapture event.

**Comment by asabaylus** [comment]
@nitishMehrotra please reach out to @ccampbell about taking on long term maintenance of mousetrap.js. It seems like the repo has fallen out of maintenance, he may be ready to turn it over. I don't think introducing a dependency on a forked repo is good long term idea as NPM exists for some very good reasons

**Pull request closed without merging**
